include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: false
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    - cancel_subscriptions
